function [State,Station_Name,Stn_ID,Stn_Num,Latitude,Longitude,Elevation_ft] = importsnotelfile(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [STATE,STATION_NAME,STN_ID,STN_NUM,LATITUDE,LONGITUDE,ELEVATION_FT] =
%   IMPORTFILE(FILENAME) Reads data from text file FILENAME for the default
%   selection.
%
%   [STATE,STATION_NAME,STN_ID,STN_NUM,LATITUDE,LONGITUDE,ELEVATION_FT] =
%   IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [State,Station_Name,Stn_ID,Stn_Num,Latitude,Longitude,Elevation_ft] =
%   importfile('SNOTEL_ALL_list.csv',2, 814);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2014/01/05 14:40:19

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Format string for each line of text:
%   column1: text (%s)
%	column2: text (%s)
%   column3: text (%s)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%s%s%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
State = dataArray{:, 1};
Station_Name = dataArray{:, 2};
Stn_ID = dataArray{:, 3};
Stn_Num = dataArray{:, 4};
Latitude = dataArray{:, 5};
Longitude = dataArray{:, 6};
Elevation_ft = dataArray{:, 7};

